name: Flutter

on:
  schedule:
    # “At 00:00 (UTC) on Sunday.”
    - cron: '0 0 * * 0'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dir: ['flutter_simple_treeview', 'linked_scroll_controller', 'scrollable_positioned_list', 'self_storing_input', 'visibility_detector']
        version: ['stable', 'master']
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.4.0
        with:
          channel: ${{ matrix.version }}

      - name: flutter version
        run: flutter --version

      - name: flutter pub get
        run: flutter pub get
        working-directory: packages/${{ matrix.dir }}

      - name: flutter analyze
        run: flutter analyze
        working-directory: packages/${{ matrix.dir }}

      - name: flutter test
        run: flutter test
        working-directory: packages/${{ matrix.dir }}
